### ISSUE TITLE
ValidationError(xrpToDrops: value '0.00620165625' has too many decimal places.)

### ISSUE THREAD

**Issue by StarNeit** [Airbitz/edge-currency-ripple#6]
I have received this error, and I can not find out why this happened when I send 6 XRP from one account to another account.

`ValidationError(xrpToDrops: value '0.00620165625' has too many decimal places.)`

`Error: Error in preparePayment`
`    at RippleEngine.makeSpend (/Volumes/MyProject/node_modules/edge-currency-ripple/lib/indexRipple.js:878:13)`
`    at <anonymous>`
`    at process._tickDomainCallback (internal/process/next_tick.js:229:7)`

It said that Error was in `preparePayment` and `makeSpend`

I think the above error is coming from the below code of ripple lib.
https://github.com/ripple/ripple-lib/blob/develop/src/common/utils.ts#L82

Can you please advice how to fix this error to send XRP?

**Comment by paullinator** [comment]
Ripple only has six decimal places. Truncate your amount and then try that again

**Comment by paullinator** [comment]
Note as well that you should not be using the Ripple library. Instead use the edge-currency-accountbased library which also includes Ripple
