### ISSUE TITLE
Does this plugin support XRP tokens too?  Can users register XRP tokens and send/receive in Edge app?

### ISSUE THREAD

**Issue by StarNeit** [Airbitz/edge-currency-ripple#7]
Does this plugin support XRP tokens too?  
Can users register XRP tokens and send/receive in Edge app?

Recently, I have decided to use XRP tokens, but I have no idea if this ripple plugin can support ripple tokens registration and trading.

Is this possible?

https://www.theworldexchange.net/#about
https://steemit.com/bitcoin/@dorming/how-to-create-your-token-on-ripple
https://xrphodor.wordpress.com/2018/01/11/tokens-trust-on-the-xrp-ledger/
https://www.reddit.com/r/XRP/comments/7q7ur9/issue_a_token_in_ripple_network/

Using the above solutions, I have created new token on ripple ledge.
Kindly let me know if Edge app's Ripple wallet can receive/send XRP tokens.

**Comment by swansontec** [comment]
This repository is currently deprecated, and all its functionality moved into https://github.com/EdgeApp/edge-currency-accountbased.

However, the answer is no, we don't actually support tokens on the Ripple network at this time.
